# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KMZI(object):
    def setupUi(self, KMZI):
        KMZI.setObjectName("KMZI")
        KMZI.setMinimumSize(QtCore.QSize(1180, 300))
        KMZI.setMaximumSize(QtCore.QSize(1500, 300))
        self.centralwidget = QtWidgets.QWidget(KMZI)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 275))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.gridLayout_2.addWidget(self.b7, 4, 3, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.gridLayout_2.addWidget(self.b4, 3, 4, 1, 1)
        self.b17 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b17.setFont(font)
        self.b17.setObjectName("b17")
        self.gridLayout_2.addWidget(self.b17, 9, 1, 1, 1)
        self.b16 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b16.setFont(font)
        self.b16.setObjectName("b16")
        self.gridLayout_2.addWidget(self.b16, 9, 3, 1, 1)
        self.b14 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b14.setFont(font)
        self.b14.setObjectName("b14")
        self.gridLayout_2.addWidget(self.b14, 7, 1, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.gridLayout_2.addWidget(self.b5, 4, 0, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.gridLayout_2.addWidget(self.b2, 3, 1, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.gridLayout_2.addWidget(self.b8, 4, 4, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.b1.setObjectName("b1")
        self.gridLayout_2.addWidget(self.b1, 3, 0, 1, 1)
        self.b13 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b13.setFont(font)
        self.b13.setObjectName("b13")
        self.gridLayout_2.addWidget(self.b13, 7, 0, 1, 1)
        self.b10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b10.setFont(font)
        self.b10.setObjectName("b10")
        self.gridLayout_2.addWidget(self.b10, 5, 1, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.gridLayout_2.addWidget(self.b3, 3, 3, 1, 1)
        self.b11 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b11.setFont(font)
        self.b11.setObjectName("b11")
        self.gridLayout_2.addWidget(self.b11, 5, 3, 1, 1)
        self.b15 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.b15.setFont(font)
        self.b15.setObjectName("b15")
        self.gridLayout_2.addWidget(self.b15, 7, 3, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.gridLayout_2.addWidget(self.b6, 4, 1, 1, 1)
        self.b12 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b12.setFont(font)
        self.b12.setObjectName("b12")
        self.gridLayout_2.addWidget(self.b12, 5, 4, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.gridLayout_2.addWidget(self.b9, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 3, 5)
        KMZI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(KMZI)
        self.statusbar.setObjectName("statusbar")
        KMZI.setStatusBar(self.statusbar)

        self.retranslateUi(KMZI)
        QtCore.QMetaObject.connectSlotsByName(KMZI)

    def retranslateUi(self, KMZI):
        _translate = QtCore.QCoreApplication.translate
        KMZI.setWindowTitle(_translate("KMZI", "MainWindow"))
        self.b7.setText(_translate("KMZI", "Диск Альберти"))
        self.b4.setText(_translate("KMZI", "Квадрат Полибия"))
        self.b17.setText(_translate("KMZI", "ШИФР ГОСТ"))
        self.b16.setText(_translate("KMZI", "ШИФР DES"))
        self.b14.setText(_translate("KMZI", "Частотный криптоанализ"))
        self.b5.setText(_translate("KMZI", "Шифр Кардано"))
        self.b2.setText(_translate("KMZI", "Шифр \"Сцитала\""))
        self.b8.setText(_translate("KMZI", "Шифр Гронсфельда"))
        self.b1.setText(_translate("KMZI", "Шифр Атбаш"))
        self.b13.setText(_translate("KMZI", "Шифрование методом гаммирования"))
        self.b10.setText(_translate("KMZI", "Шифр Плейфера"))
        self.b3.setText(_translate("KMZI", "Шифр Цезаря"))
        self.b11.setText(_translate("KMZI", "Криптосистема Хилла"))
        self.b15.setText(_translate("KMZI", "Криптоанализ полиалфавитных шифров"))
        self.b6.setText(_translate("KMZI", "Шифр Ришелье"))
        self.b12.setText(_translate("KMZI", "Шифр Вернама"))
        self.b9.setText(_translate("KMZI", "Шифр Виженера"))
        self.label.setText(_translate("KMZI", "Программный комплекс реализующий симметричные шифры от самых старых до относительно новых"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KMZI = QtWidgets.QMainWindow()
    ui = Ui_KMZI()
    ui.setupUi(KMZI)
    KMZI.show()
    sys.exit(app.exec_())
